version: '3.3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123tyso
      MYSQL_DATABASE: 123tyso
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  api:
    image: sethsandaru/php73-phalcon-laravel-fpm:1.0.0
    container_name: api
    ports:
      - 80:80
    environment:
      XDEBUG_ENABLE: 1
      XDEBUG_PORT: 9200
    volumes:
      - ./crawler-score:/var/www/html
    links:
      - db:db
      - selenium-hub:selenium-hub
      - selenium-chrome:selenium-chrome
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:3.141.59-20210105
    ports:
      - "4444:4444"
      
  selenium-chrome:
    image: selenium/node-chrome-debug:3.141.59-20210105
    shm_size: '6gb'
    ports:
      - "15900:5900"
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 7
      NODE_MAX_SESSION: 7
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1200
  # socket.io:
  #   image: node:alpine
  #   volumes:
  #     - ./socket.io:/app
  #   working_dir: /app
  #   command: npm start
networks:
  default:
    name: end-to-end-test
