version: '3.3'
services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '8080:80'
      restart: always
      environment:
          PMA_HOST: db
      depends_on:
          - db    
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: live_score
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  php:
    image: sethsandaru/php73-phalcon-laravel-fpm:1.0.0
    container_name: crawler
    ports:
      - 81:80
    environment:
      XDEBUG_ENABLE: 1
      XDEBUG_PORT: 9200
    volumes:
      - ./crawler-score:/var/www/html
    links:
      - db:db
  cron:
    image: alpine:3.12
    command: crond -f -d 8
    volumes:
      - ./cronjobs:/etc/crontabs
    entrypoint: ["crond", "-f", "-d", "8"]
    restart: always